biscuit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('marie/', include('marie.urls')),
]

marie/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt

app_name = 'marie'

urlpatterns = [
    path('', csrf_exempt(MarieWelcome.as_view()), name='index'),
    path('register', csrf_exempt(MarieRegister.as_view()), name='register'),
    path('login', csrf_exempt(MarieLogin.as_view()), name='login'),
    path('get_user', csrf_exempt(MarieGetUser.as_view()), name='get_user'),
]

marie/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fp_template_base64 = models.TextField()
    fp_bmp_base64 = models.TextField(null=True, blank=True)
    fp_encode_wsq = models.TextField(null=True, blank=True)
    fp_image_dimension = models.CharField(max_length=255, blank=True)
    fp_image_nfiq = models.TextField(null=True, blank=True)
    fp_image_wsq_size = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.user.username

# @receiver(post_save, sender=User)
# def update_user_profile(sender, instance, created, **kwargs):
#     if created:
#         UserProfile.objects.create(user=instance)
#     instance.save()

marie/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegistrationForm(UserCreationForm):
    fp_template_base64 = forms.CharField(widget=forms.Textarea)
    fp_bmp_base64 = forms.CharField(widget=forms.Textarea, required=False)
    fp_encode_wsq = forms.CharField(widget=forms.Textarea, required=False)
    fp_image_nfiq = forms.CharField(widget=forms.Textarea, required=False)
    fp_image_wsq_size = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'fp_template_base64', 'fp_bmp_base64', 'fp_encode_wsq', 'fp_image_nfiq', 'fp_image_wsq_size')

marie/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, View
from django.shortcuts import get_object_or_404, redirect
from .models import UserProfile
from django.contrib.auth.models import User
from .forms import UserRegistrationForm
from django.contrib.auth import login, authenticate


# Create your views here.
class MarieLogin(View):
    
    def get(self, request):
        form = UserRegistrationForm()
        return render(request, 'login.html', {"form": form})

    def post(self, request):
        username = request.POST.get('username')
        user = User.objects.get(username=username)
        userauthenticate = authenticate(username=username, password=user.password)
        login(request, user)
        return redirect('marie:index')

class MarieWelcome(View):

    def get(self, request):
        user = request.user
        return render(request, 'index.html', {"user": user})

class MarieGetUser(View):
    
    def post(self, request):
        username = request.POST.get('username')
        user = User.objects.get(username=username)
        # print(user.password)
        userprofile = UserProfile.objects.get(user=user.id)
        template_base64_response = userprofile.fp_template_base64
        return HttpResponse(template_base64_response, status=200)


class MarieRegister(View):

    def get(self, request):
        form = UserRegistrationForm()
        return render(request, 'register.html', {"form": form})

    def post(self, request):
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST.get('username')
            fp_template_base64 = request.POST.get('fp_template_base64')
            fp_bmp_base64 = request.POST.get('fp_bmp_base64')
            fp_encode_wsq = request.POST.get('fp_encode_wsq')
            fp_image_height = request.POST.get('fp_image_height')
            fp_image_width = request.POST.get('fp_image_width')
            fp_image_resolution = request.POST.get('fp_image_resolution')
            fp_image_quality = request.POST.get('fp_image_quality')
            fp_image_nfiq = request.POST.get('fp_image_nfiq')
            fp_image_wsq_size = request.POST.get('fp_image_wsq_size')
            fp_image_dimension = {
                "height": fp_image_height,
                "width": fp_image_width,
                "resolution": fp_image_resolution,
                "quality": fp_image_quality
            }
            user = User.objects.get(username=username)
            user_profile = UserProfile(
                user_id=user.id,
                fp_template_base64=fp_template_base64,
                fp_bmp_base64=fp_bmp_base64,
                fp_encode_wsq=fp_encode_wsq,
                fp_image_dimension=fp_image_dimension,
                fp_image_nfiq=fp_image_nfiq,
                fp_image_wsq_size=fp_image_wsq_size
            )
            user_profile.save()
            print('profile saved', fp_image_dimension, username)
        else:
            print('invalid')
        return HttpResponse('nice, a successfull post request on my index page, hmm', status=200)

marie/templates/index.html
welcome to our site {{ user }}

marie/templates/login.html
hello please login!
<hr>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<form method="POST" action="{% url 'marie:login' %}" id="login-form">
    {% csrf_token %}

    <input id="id_username" name="username" type="text" placeholder="Username">

    
    <input id="id_template_base64_1" name="template_base64_1" type="text" style="display:none">
    <input id="id_template_base64_2" name="template_base64_2" type="text" style="display:none">
    <input type='text' id=quality size=10 value="100" style="display:none">
    
    <p>Scan your fingerprint for identification</p>
    <input type="button" value="Click to scan fingerprint" onclick="captureFP()" />
</form>

<div id="status-div">

</div>
<script type="text/javascript">
    var template1 = "";
    var template2 = "";
    var secugen_lic = "";
    
    function captureFP() {
        CallSGIFPGetData(SuccessFunc, ErrorFunc);
    }

    $('#id_username').focusout(function(){
        var username = $(this).val()
        $.ajax({
            url: 'get_user',
            type: 'POST',
            dataType: 'text',
            data: {'username': username},
            success: function (res) {
                var template1 = res
                document.getElementById('id_template_base64_1').value = res
            },
            error: function(e) {},
        })
    });

    function SuccessFunc(result) {
        if (result.ErrorCode == 0) {
            template1 = $('#id_template_base64_1').val()
            template2 = result.TemplateBase64

            matchScore(succMatch, failureFunc, template1, template2)
        }
        else {
            document.getElementById("status-div").innerHTML = "<i>Fingerprint Capture Error Code:  " + result.ErrorCode + ".\nDescription:  " + ErrorCodeToString(result.ErrorCode) + ".</i>"
        }
    }

    function ErrorFunc(status) {
        document.getElementById("status-div").innerHTML = "<i>Check if SGIBIOSRV is running; Status = " + status + " Fingerprint Scanner not Connected. </i>"
    }

    function CallSGIFPGetData(successCall, failCall) {
        // 8.16.2017 - At this time, only SSL client will be supported.
        var uri = "https://localhost:8443/SGIFPCapture";
        var secugen_lic = "";

        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                fpobject = JSON.parse(xmlhttp.responseText);
                successCall(fpobject);
            }
            else if (xmlhttp.status == 404) {
                failCall(xmlhttp.status)
            }
        }
        var params = "Timeout=" + "10000";
        params += "&Quality=" + "50";
        params += "&licstr=" + encodeURIComponent(secugen_lic);
        params += "&templateFormat=" + "ISO";
        params += "&imageWSQRate=" + "0.75";
        console.log
        xmlhttp.open("POST", uri, true);
        xmlhttp.send(params);

        xmlhttp.onerror = function () {
            failCall(xmlhttp.statusText);
        }
    }

    function matchScore(succFunction, failFunction, template1, template2) {
        var uri = "https://localhost:8443/SGIMatchScore";

        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                fpobject = JSON.parse(xmlhttp.responseText);
                succFunction(fpobject);
            }
            else if (xmlhttp.status == 404) {
                failFunction(xmlhttp.status)
            }
        }

        xmlhttp.onerror = function () {
            failFunction(xmlhttp.status);
        }
        var params = "template1=" + encodeURIComponent(template1);
        params += "&template2=" + encodeURIComponent(template1);
        params += "&licstr=" + encodeURIComponent(secugen_lic);
        params += "&templateFormat=" + "ISO";
        xmlhttp.open("POST", uri, false);
        xmlhttp.send(params);
    }

    function succMatch(result) {
        var idQuality = document.getElementById("quality").value;
        if (result.ErrorCode == 0) {
            if (result.MatchingScore >= idQuality) {
                document.getElementById("status-div").innerHTML = "<i>Fingerprint matched.</i>"
                
                var username = $('#id_username').val()
                setTimeout(function(){
                    alert('redirecting you to home.')
                    $('#login-form').submit()
                }, 1500)
            }
            else
                alert("NOT MATCHED ! (" + result.MatchingScore + ")");
        }
        else {
            alert("Error Scanning Fingerprint ErrorCode = " + result.ErrorCode);
        }
    }

    function failureFunc(error) {
        alert ("On Match Process, failure has been called");
    }
</script>

marie/templates/register.html
hello!
<form method="POST" action="{% url 'marie:register' %}">
    {% csrf_token %}

    <input id="id_username" name="username" type="text" placeholder="Username">
    <input id="id_password1" name="password1" type="password" placeholder="Password">
    <input id="id_password2" name="password2" type="password" placeholder="Confirm Password">
    <input id="id_fp_template_base64" name="fp_template_base64" type="text" style="display:none">
    <input id="id_fp_bmp_base64" name="fp_bmp_base64" type="text" style="display:none">
    <input id="id_fp_encode_wsq" name="fp_encode_wsq" type="text" style="display:none">
    <input id="id_fp_image_height" name="fp_image_height" type="text" style="display:none">
    <input id="id_fp_image_width" name="fp_image_width" type="text" style="display:none">
    <input id="id_fp_image_resolution" name="fp_image_resolution" type="text" style="display:none">
    <input id="id_fp_image_quality" name="fp_image_quality" type="text" style="display:none">
    <input id="id_fp_image_nfiq" name="fp_image_nfiq" type="text" style="display:none">
    <input id="id_fp_image_wsq_size" name="fp_image_wsq_size" type="text" style="display:none">

    <input type="submit" id="form-submit" disabled/>
</form>


<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<p>Scan your fingerprint for identification registration</p>
<input type="button" value="Click to scan fingerprint" onclick="captureFP()" />

<div id="status-div">

</div>
<script type="text/javascript">
    function captureFP() {
        CallSGIFPGetData(SuccessFunc, ErrorFunc);
    }

    function SuccessFunc(result) {
        if (result.ErrorCode == 0) {
            /* 	Display BMP data in image tag
                BMP data is in base 64 format 
            */

            document.getElementById("id_fp_template_base64").value = result.TemplateBase64
            document.getElementById("id_fp_bmp_base64").value = result.BMPBase64
            document.getElementById("id_fp_encode_wsq").value = result.WSQImage
            document.getElementById("id_fp_image_height").value = result.ImageHeight
            document.getElementById("id_fp_image_width").value = result.ImageWidth
            document.getElementById("id_fp_image_resolution").value = result.ImageDPI
            document.getElementById("id_fp_image_quality").value = result.ImageQuality
            document.getElementById("id_fp_image_nfiq").value = result.NFIQ
            document.getElementById("id_fp_image_wsq_size").value = result.WSQImageSize
            document.getElementById("status-div").innerHTML = "<i>Fingerprint captured.</i>"
            $('#form-submit').removeAttr("disabled");
        }
        else {
            document.getElementById("status-div").innerHTML = "<i>Fingerprint Capture Error Code:  " + result.ErrorCode + ".\nDescription:  " + ErrorCodeToString(result.ErrorCode) + ".</i>"
        }
    }

    function ErrorFunc(status) {
        document.getElementById("status-div").innerHTML = "<i>Check if SGIBIOSRV is running; Status = " + status + " Fingerprint Scanner not Connected. </i>"
    }


    function CallSGIFPGetData(successCall, failCall) {
        // 8.16.2017 - At this time, only SSL client will be supported.
        var uri = "https://localhost:8443/SGIFPCapture";
        var secugen_lic = "";

        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                fpobject = JSON.parse(xmlhttp.responseText);
                successCall(fpobject);
            }
            else if (xmlhttp.status == 404) {
                failCall(xmlhttp.status)
            }
        }
        var params = "Timeout=" + "10000";
        params += "&Quality=" + "50";
        params += "&licstr=" + encodeURIComponent(secugen_lic);
        params += "&templateFormat=" + "ISO";
        params += "&imageWSQRate=" + "0.75";
        console.log
        xmlhttp.open("POST", uri, true);
        xmlhttp.send(params);

        xmlhttp.onerror = function () {
            failCall(xmlhttp.statusText);
        }
    }
</script>